roc-api:
  image:
    registry: kapfzoie001.ka.intel.com:31555
    repository: sra_0_1_x/roc-rest-api
    pullPolicy: IfNotPresent

roc-gui:
  image:
    registry: kapfzoie001.ka.intel.com:31555
    repository: roc-ui
    pullPolicy: IfNotPresent

onos-config:
  modelPlugins:
    - name: sra-0-1
      image: kapfzoie001.ka.intel.com:31555/onosproject/sra-0.1.x:0.1.0-dev-sra-0.1.x
      endpoint: localhost
      port: 5152
