# yaml-language-server: $schema=/tmp/schemas/application.yaml#/CASpecApplications
---
specSchema: "CompositeApp_Applications"
schemaVersion: "0.1"
applications:
  - appName: sra-evam-helm                    # EMCO expects this to be the same as chart name
    source:
      filename: sra-app/sra-evam-helm-0.1.0.tgz
  - appName: rocaas-umbrella                  # EMCO expects this to be the same as chart name
    source:
      filename: sra-roc/rocaas-umbrella-0.1.0.tgz
